#!/usr/bin/env python3
"""
Normalize Naruto Ultimate Ninja Storm 1 command-chart research into a stable
JSON format that can be consumed by this project.

Input format:
  JSON generated by NUNSMOD's command_chart_tool.py "extract" command.
  The external tool is NOT vendored here.

This bridge does not extract or redistribute game assets. It only transforms
metadata/text the user has already produced locally from files they supplied.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

DEFAULT_CHARACTER_MAP = {
    "cmd1nrt": "naruto",
    "cmd1ssk": "sasuke",
}

SCHEMA_VERSION = 1


def _numeric_neighbors(entries: list[dict[str, Any]], index: int, radius: int = 3) -> dict[str, list[dict[str, int]]]:
    before: list[dict[str, int]] = []
    after: list[dict[str, int]] = []

    for item in entries[max(0, index - radius):index]:
        if item.get("kind") == "num":
            before.append({
                "index": int(item.get("index", -1)),
                "value": int(item.get("value", 0)),
            })

    for item in entries[index + 1:index + 1 + radius]:
        if item.get("kind") == "num":
            after.append({
                "index": int(item.get("index", -1)),
                "value": int(item.get("value", 0)),
            })

    return {"before": before, "after": after}


def normalize_command_chart(
    payload: dict[str, Any],
    character_map: dict[str, str] | None = None,
) -> dict[str, Any]:
    mapping = dict(DEFAULT_CHARACTER_MAP)
    if character_map:
        mapping.update(character_map)

    characters: dict[str, Any] = {}
    unknown_chunks: dict[str, Any] = {}

    for chunk_name in sorted(payload.keys()):
        raw_entries = payload[chunk_name]
        if not isinstance(raw_entries, list):
            continue

        normalized_entries: list[dict[str, Any]] = []
        text_count = 0
        numeric_count = 0

        for position, item in enumerate(raw_entries):
            if not isinstance(item, dict):
                continue

            kind = str(item.get("kind", "unknown"))
            source_index = int(item.get("index", position))
            value = item.get("value")

            normalized: dict[str, Any] = {
                "source_index": source_index,
                "kind": kind,
            }

            if kind == "text":
                text_count += 1
                normalized["text"] = str(value)
                normalized["numeric_context"] = _numeric_neighbors(raw_entries, position)
            elif kind == "num":
                numeric_count += 1
                try:
                    normalized["value"] = int(value)
                except (TypeError, ValueError):
                    normalized["value"] = value
            else:
                normalized["value"] = value

            normalized_entries.append(normalized)

        record = {
            "source_chunk": chunk_name,
            "text_fields": text_count,
            "numeric_fields": numeric_count,
            "fields": normalized_entries,
        }

        character_id = mapping.get(chunk_name)
        if character_id:
            characters[character_id] = record
        else:
            unknown_chunks[chunk_name] = record

    return {
        "schema_version": SCHEMA_VERSION,
        "source_format": "NUNSMOD command_chart_tool extract JSON",
        "characters": characters,
        "unknown_chunks": unknown_chunks,
        "notes": [
            "Text labels and adjacent integers are preserved for research.",
            "Numeric fields are not automatically interpreted as damage, timing, hitbox or chakra.",
            "Do not transplant raw numeric values into Godot until the field meaning and unit are verified.",
        ],
    }


def load_character_map(path: Path | None) -> dict[str, str]:
    if path is None:
        return {}
    with path.open("r", encoding="utf-8") as handle:
        payload = json.load(handle)
    if not isinstance(payload, dict):
        raise ValueError("character map must be a JSON object")
    return {str(key): str(value) for key, value in payload.items()}


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Normalize NUNSMOD CommandChartData JSON for Shinobi RPG research."
    )
    parser.add_argument("input_json", type=Path)
    parser.add_argument("output_json", type=Path)
    parser.add_argument(
        "--character-map",
        type=Path,
        default=None,
        help='Optional JSON object such as {"cmd1kks": "kakashi"}.',
    )
    args = parser.parse_args()

    with args.input_json.open("r", encoding="utf-8") as handle:
        payload = json.load(handle)
    if not isinstance(payload, dict):
        raise ValueError("input must be a JSON object keyed by XFBIN chunk name")

    result = normalize_command_chart(payload, load_character_map(args.character_map))

    args.output_json.parent.mkdir(parents=True, exist_ok=True)
    with args.output_json.open("w", encoding="utf-8") as handle:
        json.dump(result, handle, ensure_ascii=False, indent=2)
        handle.write("\n")

    known = ", ".join(sorted(result["characters"].keys())) or "none"
    print(f"Normalized command chart: {known}")
    print(f"Unknown chunks preserved: {len(result['unknown_chunks'])}")
    print(f"Wrote: {args.output_json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
